Universe = vanilla
Executable = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main_shower.sh
Arguments = $(seed)
Output = log/condor_shower_$(Cluster)_$(Process).stdout
Error = log/condor_shower_$(Cluster)_$(Process).stderr
Log = log/condor_shower_$(Cluster)_$(Process).log
Should_Transfer_Files = YES
Transfer_Input_Files = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/condor_submit_shower.tar, \
                       /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main_shower.sh
request_memory = 10GB
request_cpus = 8
request_disk = 5G
WhenToTransferOutput = ON_EXIT
+JobFlavour = "workday"
Queue seed from /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/seeds.txt
