Universe = vanilla
Executable = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main.sh
Arguments = $(seed)
Should_Transfer_Files = YES
Transfer_Input_Files = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/condor_submit.tar, \
                       /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main.sh
Transfer_Output_Files = sample_pp_nonia_mps.lhe
Transfer_Output_Remaps = "sample_pp_nonia_mps.lhe = /eos/user/c/chiw/JpsiJpsiUps/MC_samples/LHE/TPS-JpsiJpsiY/sample_pp_nonia_mps_helac_$(Process).lhe"
request_memory = 15GB
request_cpus = 8
request_disk = 8G
WhenToTransferOutput = ON_EXIT
Output = log/condor_treewriter_$(Cluster)_$(Process).stdout
Error = log/condor_treewriter_$(Cluster)_$(Process).stderr
Log = log/condor_treewriter_$(Cluster)_$(Process).log
Queue seed from /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/seeds.txt