Universe = vanilla
Executable = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main_full.sh
Arguments = $(seed)
Output = log/condor_full_$(Cluster)_$(Process).stdout
Error = log/condor_full_$(Cluster)_$(Process).stderr
Log = log/condor_full_$(Cluster)_$(Process).log
Should_Transfer_Files = YES
Transfer_Input_Files = /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/condor_submit_full.tar, \
                       /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/main_full.sh
request_memory = 15GB
request_cpus = 8
request_disk = 8G
WhenToTransferOutput = ON_EXIT
+JobFlavour = "workday"
Queue seed from /afs/cern.ch/user/c/chiw/condor/HELAC-on-HTCondor/seeds.txt
